spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.811f6c851fbef59a
            clientSecret: e12ce2f7cfcbadebfe8f4ae99359612a9b35df81
#            clientSecret: SHA256:bLtJ2XB6Kv6rawgickZgGZA1NBLpQRUEd2yQJHP5/HE=
          google:
            clientId: 1010975806783-jvga3rtqmrdnnmv1k03hr32q30n48e6v.apps.googleusercontent.com
            clientSecret: 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

frontend:
  url: http://localhost:5000

logging:
  level:
    org:
      springframework:
        security: DEBUG