spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso_test
    username: sheru
    password: Shreyans@2801
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.811f6c851fbef59a
            clientSecret: e12ce2f7cfcbadebfe8f4ae99359612a9b35df81
          google:
            clientId: 1010975806783-jvga3rtqmrdnnmv1k03hr32q30n48e6v.apps.googleusercontent.com
            clientSecret: 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
  error:
    include-message: always

frontend:
  url: http://localhost:5000

logging:
  level:
    org:
      springframework:
        security: DEBUG

